defaultErrorMessage: Mohon maaf sebelumnya ada error di sistem kami nih :(
botDisplayName: Hobo
companyName: AEON
companyAddress: Jl. Mandar dalam no 19 RT/RW.03/05, pondok karya, pondok aren, tangerang selatan.
companyImage: https://media.travelingyuk.com/wp-content/uploads/2017/08/FI-hotel-bali.jpg
companyImage2: https://i.pinimg.com/originals/e4/dd/ab/e4ddab390a3c9a36a2262dba0dade873.jpg
Room: Single, Twin, Superior Single, Superior Twin, dan Familiy Room